modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.jjcommands]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jjcommands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="jjcommands"
version="1.0.0"
displayName="JujutsuCraft Commands"
description="Adds /roll and /grant commands"
